NO_CHATROOM_NAME = {'error_code': 'CHAT-1', 'message': 'name is none'}
NO_ROOM_PK = {'error_code': 'CHAT-2', 'message': 'room_pk is none'}
# CHATROOM_ALREADY_EXISTS = {'error_code': 'CHAT-3', 'message': 'Chatroom with this name already exists'}
NO_LAST_MESSAGE = {'error_code': 'CHAT-4', 'message': 'Message with pk last_message does not exists'}
LAST_MESSAGE_INT = {'error_code': 'CHAT-5', 'message': 'last_message is not int'}
USER_NOT_ADMIN = {'error_code': 'CHAT-6', 'message': 'User (you) is not chatroom admin'}
NO_USER_WITH_PK = {'error_code': 'CHAT-7', 'message': 'User with this pk does not exists'}
USER_IS_NONE = {'error_code': 'CHAT-8', 'message': 'user is none'}
SAME_INVITATION_EXISTS = {'error_code': 'CHAT-9', 'message': 'That invitation already exists'}
INVITATION_DOESNT_EXISTS = {'error_code': 'CHAT-10', 'message': 'This invitation does not exists'}
NO_NAME = {'error_code': 'CHAT-10', 'message': 'name is none or empty'}
USER_IS_MEMBER = {'error_code': 'CHAT-11', 'message': 'This user is already member'}
CANT_INVITE_YOURSELF = {'error_code': 'CHAT-12', 'message': 'You can not invite yourself'}
USER_NOT_MEMBER = {'error_code': 'CHAT-13', 'message': 'User is not chatroom member'}
PK_USER_NOT_MEMBER = {'error_code': 'CHAT-14', 'message': 'User with pk user is not chatroom member'}
PK_USER_NOT_ADMIN = {'error_code': 'CHAT-15', 'message': 'User with pk user is not chatroom admin'}
TOO_LESS_CREATORS = {'error_code': 'CHAT-16', 'message': 'There needs to be at least 1 creator'}
CANT_REMOVE_YOURSELF = {'error_code': 'CHAT-17', 'message': 'You can not remove yourself'}
INVALID_EXTENSION = {'error_code': 'CHAT-18', 'message': 'Invalid file extension'}
NO_PICTURE = {'error_code': 'CHAT-19', 'message': 'image is none'}
